en:
  GuildName: Bearded Legends
  GuildNameDecorative: ⎯ Bearded ✦ Legends ⎯
  GameName: Knighthood
  WelcomeMessage: Welcome to ${place}
  AddButtonLabel: Add
  WarTimerAppName: War Timer
es:
  Greeting: ¡Hola, ${name}!
