en:
  GuildName: Bearded Legends
  GuildNameDecorative: ⎯ Bearded ✦ Legends ⎯
  GameName: Knighthood
  WelcomeMessage: Welcome to ${place}
  WarTimerAppName: War Timer
  ChatAppName: Discord
  AddButtonLabel: Add
es:
  Greeting: ¡Hola, ${name}!
