en:
  SettingsScreenHeader: ${SettingsScreenName}
  AccessibilitySettingsHeader: Accessibility
  AccessibilitySettings:
    ZoomInButtonLabel: Zoom in
    ZoomFieldSetLabel: Zoom
    ZoomOutButtonLabel: Zoom out
  SoftwareUpdatesHeader: Software update
  SoftwareUpdates:
    AppVersionLabel: App version
    AvailableAppVersionLabel: Available version
    SoftwareUpdatesErrorMessage: Failed to retrieve available version.
    SoftwareUpdatesStatusMessage:
      UP_TO_DATE: Your app is up-to-date.
    ReloadButtonLabel: Reload your app
    UpdateButtonLabel: Update your app
